/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include"opencv2/opencv.hpp"
/* Header for class com_example_usmanarshad_myapplication_Opencvclass */
using namespace cv;
#ifndef _Included_com_example_usmanarshad_myapplication_Opencvclass
#define _Included_com_example_usmanarshad_myapplication_Opencvclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_usmanarshad_myapplication_Opencvclass
 * Method:    faceDetection
 * Signature: (Ljava/lang/Long;)V
 */
 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_example_usmanarshad_myapplication_Opencvclass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
